### ISSUE TITLE
CI checks out `orchestra` `master` instead of `next-master` when pushing on `master` on some other repo

### ISSUE THREAD

**Issue by aleclearmind** [revng/orchestra#44]
If I push the `master` branch of `llvm-project`, the CI is triggered with `COMPONENT_TARGET_BRANCH=master`.
This leads to check out the `master` branch of `orchestra`, which is undesired.

I suggest we blacklist `master`, `develop`, `next-master` and `next-develop` from being considered in `COMPONENT_TARGET_BRANCH`. I think the use case for `COMPONENT_TARGET_BRANCH` is just for `feature/...` branches.

@fcremo, what do you think?

**Comment by fcremo** [comment]
For future reference after IRL conversation: we convened the situation is not ideal but not worth addressing right now.
This behavior is problematic when force pushing changes to e.g. llvm `master` that also require updates to the orchestra config. There is a workflow that works around the issue:

- force-push llvm `master` and `next-master`
  - pushing to both is required since orchestra promotes a branch only if it can be fast-forwarded
  - these pushes will trigger the CI (twice), which will fail (as it will use the old orchestra config)
- push orchestra `next-master`
  - orchestra will checkout llvm `next-master`, build it, and if everything goes well it will promote `next-master` to `master`

**Comment by aleclearmind** [comment]
Thanks! Closing this.
